uploads = []

[[generated]]
id = "vDW9NLzXFQbpoGhwnWncn"
uri = "file://artifacts/mobile/assets/images/app-icon.png"
type = "image"
title = "TDMS app icon navy truck"

[[outputs]]
id = "3BgwGMYMxNsrN0_srjr-o"
uri = "file://screenshots/jobs-tab.jpg"
type = "image"
title = "TDMS Mobile - Job Bookings Tab"

[[outputs]]
id = "n1MZg4AvETGsgLk1nVy9c"
uri = "file://screenshots/jobs-tab-air-cargo.jpg"
type = "image"
title = "TDMS Mobile - Job Bookings (Air Cargo workflow available)"
